name: Build Android App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential \
            git \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libssl-dev \
            libreadline-dev \
            libffi-dev \
            libsqlite3-dev \
            libbz2-dev \
            openjdk-17-jdk \
            unzip \
            zip \
            ccache

      - name: Setup Android SDK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          # Установка Command Line Tools
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest
          
          # Настройка PATH
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          
          # Принятие лицензий
          yes | sdkmanager --licenses
          
          # Установка компонентов
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653"

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip wheel
          pip3 install buildozer cython==0.29.36 sh==2.0.6
          pip3 install git+https://github.com/kivy/python-for-android.git

      - name: Initialize Buildozer
        run: |
          buildozer android update
          buildozer android clean

      - name: Build APK
        run: |
          buildozer -v android debug
          ls -la bin/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: bin/*.apk
