name: Build Android App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            unzip \
            zip \
            git

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: 25.2.9519653
          build-tools-version: 34.0.0
          platforms: android-34

      - name: Install Buildozer with fixed p4a
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.36
          # Устанавливаем p4a напрямую из репозитория
          rm -rf ~/.buildozer/android/platform/python-for-android
          git clone https://github.com/kivy/python-for-android.git \
            ~/.buildozer/android/platform/python-for-android

      - name: Clean build
        run: |
          buildozer android clean
          rm -rf .buildozer

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
