name: Build Android App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential \
            git \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libssl-dev \
            libreadline-dev \
            libffi-dev \
            libsqlite3-dev \
            libbz2-dev \
            openjdk-17-jdk \
            unzip \
            zip \
            ccache

      - name: Setup Android SDK
        run: |
          export ANDROID_HOME="$HOME/android-sdk"
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          
          mkdir -p $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools/* "$ANDROID_HOME/cmdline-tools/latest"
          
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;25.2.9519653"
          
          chmod +x $ANDROID_HOME/build-tools/34.0.0/aidl
          ls -l $ANDROID_HOME/build-tools/34.0.0/aidl

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip wheel
          pip3 install buildozer cython==0.29.36

      - name: Cache Buildozer
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.android
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug
          ls -la bin/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: bin/*.apk
