name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./artifact
      # Шаг 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2. Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Шаг 3. Установка зависимостей системы и Python
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk
          pip install --upgrade pip buildozer cython==0.29.21 virtualenv

      # Шаг 4. Запуск Buildozer для сборки APK
      - name: Build APK with Buildozer
        run: |
          buildozer android debug
          ls -la bin/

      # Шаг 5. Сохранение собранного APK как артефакт сборки
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mykivymdapp-apk
          path: bin/*.apk
