name: Build Android App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential \
            git \
            zlib1g-dev \
            libncurses5-dev \
            libgdbm-dev \
            libnss3-dev \
            libssl-dev \
            libreadline-dev \
            libffi-dev \
            libsqlite3-dev \
            libbz2-dev \
            openjdk-17-jdk \
            unzip \
            zip \
            ccache

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: 23.1.7779620  # Соответствует android.ndk = 23b
          build-tools-version: 34.0.0
          platform-tools-version: 34.0.0
          platforms-version: "android-33"

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip wheel
          pip3 install buildozer cython==0.29.36
          pip3 install python-for-android==2023.08.25  # Явная установка p4a

      - name: Initialize Buildozer
        run: |
          buildozer init
          buildozer android update  # Ключевой шаг!

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug
          ls -la bin/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: bin/*.apk
